// app/layout.tsx
"use client"
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import "./globals.css";
import ProgressBar from './ProgressBar'; // Импортируйте ProgressBar
import Head from 'next/head'; // Добавьте этот импорт
config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
      </Head>
      <html lang="en">
        <body>
          <ProgressBar />
          {children}
        </body>
      </html>
    </>
  );
}
